routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

//  Route::get('/home', 'HomeController@index')->name('home');

/*
 * Barbecue Routes
 */

Route::group([
    'namespace' => 'Barbecue'
], function () {
    Route::get('/', 'BarbecueController@index');

    Route::group([
        'middleware' => 'auth'
    ], function () {
        Route::resource('barbecues', 'BarbecueController');
        Route::get('my-barbecues', 'BarbecueController@showByUser')->name('barbecues.byUser');
        Route::get('api/barbecues/availables', 'BarbecueController@getAvailable')->name('barbecues.api.availables');
        Route::get('availables', 'BarbecueController@showAvailable')->name('barbecues.availables');

        Route::resource('reservations', 'ReservationController');
        Route::get('/my-reservations', 'ReservationController@showByUser')->name('reservations.byUser');
    });
});

app/User.php
<?php

namespace App;

use App\Entities\Barbecue;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /*
     * relationships
     */

    public function barbecues()
    {
        return $this->hasMany(Barbecue::class);
    }
}

app/Http/Controllers/Barbecue/BarbecueController.php
<?php

namespace App\Http\Controllers\Barbecue;

use App\Entities\Barbecue;
use App\Http\Controllers\Controller;

use App\Services\BarbecueService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class BarbecueController extends Controller
{
    private $barbecueService;

    public function __construct(BarbecueService $barbecueService)
    {
        $this->barbecueService = $barbecueService;
    }

    public function index()
    {
        $barbecues = $this->barbecueService->getAll(8);
        return view('barbecue.index', compact('barbecues'));
    }

    public function show(Barbecue $barbecue)
    {
        return view('barbecue.show', compact('barbecue'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'image' => 'required|image|mimes:jpeg,png,jpg|max:2048'
        ]);

        $image = $request->file('image');
        //$fileName = $image->getFilename() . '-' . time() . '.' .$image->getClientOriginalExtension();
        $fileName =  Storage::disk(env('STORAGE_DISK'))->put('', $image, 'public');
        //$image->storeAs(env('STORAGE_DISK'), $fileName);

        $data = $request->input();
        $coordinates = $data['coordinates'];    

        $data['image'] = $fileName;
        $data['user_owner'] = Auth::id();
        $data['coordinates'] = DB::raw("POINT($coordinates)");

        $data = $this->barbecueService->create($data);

        return response()->json($data, 201);
    }

    public function showByUser()
    {
        $authId = Auth::id();
        $barbecues = $this->barbecueService->getbyUser($authId, 25);
        return view('barbecue.show-by-user', compact('barbecues'));
    }

    public function create()
    {
        return view('barbecue.create');
    }

    public function getAvailable(Request $request)
    {
        $ubication = $request->query('ubication');
        $km = $request->query('meters', 5000);

        $barbecues = $this->barbecueService->listByDistance($ubication, $km, 8);
        return response()->json($barbecues, 200);
    }

    public function showAvailable()
    {
        return view('barbecue.availables');
    }
}

app/Http/Controllers/Barbecue/ReservationController.php
<?php

namespace App\Http\Controllers\Barbecue;

use App\Entities\Reservation;
use App\Http\Requests\ReservationFormRequest;
use App\Services\ReservationService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ReservationController extends Controller
{
    private $reservationService;

    public function __construct(ReservationService $reservationService)
    {
        $this->reservationService = $reservationService;
    }

    public function index()
    {

    }

    public function store(ReservationFormRequest $request)
    {
        $client = $request->user();
        $data = $request->input();
        $result = false;

        try{
            $result = $this->reservationService->save($data, $client);
        }catch (\Exception $exception)
        {
            $message = 'Lo sentimos, ha ocurrido un problema';
            $code = 500;
            if($exception->getCode() == 400) {
                $message = $exception->getMessage();
                $code = $exception->getCode();
            }
            return response()->json(['body' => $message], $code);
        }

        return response()->json($request->all(), 201);
    }

    public function showByUser()
    {
        $authId = Auth::id();
        $reservations = Reservation::with(['barbecue'])->where('user_client', $authId)->paginate(10);
        return view('reservation.show-by-user', compact('reservations'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/barbecue/availables.blade.php
@extends('layouts.master')

@section('title')
    Barbacoas Disponibles
@endsection

@section('content')
    <barbecue-available
            route-available="{{ route('barbecues.api.availables') }}"
            route-barbecue="{{ route('barbecues.index') }}">
    </barbecue-available>
@endsection

resources/views/barbecue/create.blade.php
@extends('layouts.master')

@section('title')
    Agregar Barbacoa
@endsection

@section('content')
    <div class="container">
        <barbecue-form-component></barbecue-form-component>
    </div>
@endsection

resources/views/barbecue/index.blade.php
@extends('layouts.master')

@section('title')
    Inicio
@endsection

@section('content')

    <section class="hero is-large container custom-hero">
        <div class="hero-body">
            <div class="container">
                <h1 class="title has-text-weight-bold has-text-light is-size-1">Encuentra una Barbacoa cerca de ti</h1>
                <a href="{{ route('barbecues.availables') }}" class="button is-light">Buscar</a>
            </div>
        </div>
    </section>

    <section class="section">
        <div class="container">
            <h1 class="title">Barbacoas Recien Agregadas</h1>
            <h2 class="subtitle">
                Comparte agradables momentos con amigos y familiares. Elige la Barbacoa que más te guste.
            </h2>
        </div>
    </section>

    <div class="container">
        @foreach ($barbecues->chunk(4) as $chunk)
            <div class="columns">
                @foreach ($chunk as $item)
                    <div class="column is-3">
                        <div class="card custom-card">
                            <div class="card-image">
                                <figure class="image is-4by3">
                                    <img src="{{ $item->image_url }}" alt="Placeholder image">
                                </figure>
                            </div>
                            <div class="card-content">
                                <div class="media">
                                    <div class="media-left">
                                        <figure class="image is-48x48">
                                            <img src="{{ asset('images/user.png') }}" alt="Placeholder image">
                                        </figure>
                                    </div>
                                    <div class="media-content">
                                        <p class="title is-4">
                                            <a class="has-text-dark" href="{{ route('barbecues.show', ['barbecue' => $item->hash]) }}">
                                                {{ $item->name }}
                                            </a>
                                        </p>
                                        <p class="subtitle is-6">{{ $item->owner->name }}</p>
                                    </div>
                                </div>
                                <div class="content">
                                    <p>{{ \Illuminate\Support\Str::limit($item->description, 150) }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        @endforeach
    </div>

@endsection

resources/views/barbecue/show-by-user.blade.php
@extends('layouts.master')

@section('title')
    Barbacoas Agregadas
@endsection

@section('content')

    <section class="section">
        <div class="container">
            <h1 class="title">Lista de tus Barbacoas</h1>
        </div>
    </section>

    <div class="container">
        @foreach ($barbecues->chunk(4) as $chunk)
            <div class="columns">
                @foreach ($chunk as $item)
                    <div class="column is-3">
                        <div class="card custom-card">
                            <div class="card-image">
                                <figure class="image is-4by3">
                                    <img src="{{ $item->image_url }}" alt="Placeholder image">
                                </figure>
                            </div>
                            <div class="card-content">
                                <div class="media">
                                    <div class="media-left">
                                        <figure class="image is-48x48">
                                            <img src="{{ asset('images/user.png') }}" alt="Placeholder image">
                                        </figure>
                                    </div>
                                    <div class="media-content">
                                        <p class="title is-4">{{ $item->name }}</p>
                                    </div>
                                </div>

                                <div class="content">
                                    <p>{{ \Illuminate\Support\Str::limit($item->description, 150) }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        @endforeach
    </div>

@endsection

resources/views/barbecue/show.blade.php
@extends('layouts.master')

@section('title')
    Reservar Barbacoa
@endsection

@section('content')
    <div class="container">
        <div class="columns">
            <div class="column is-4">
                <div class="card">
                    <div class="card-image">
                        <figure class="image is-4by3">
                            <img src="{{ $barbecue->image_url }}" alt="Placeholder image">
                        </figure>
                    </div>
                    <div class="card-content">
                        <div class="media">
                            <div class="media-left">
                                <figure class="image is-48x48">
                                    <img src="{{ asset('images/user.png') }}" alt="Placeholder image">
                                </figure>
                            </div>
                            <div class="media-content">
                                <p class="title is-4">{{ $barbecue->name }}</p>
                                <p class="subtitle is-6">{{$barbecue->owner->name  }}</p>
                            </div>
                        </div>

                        <div class="content">
                            <p>{{ $barbecue->description  }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-8">
                <reservation-form-component barbecue="{{ $barbecue->hash }}"></reservation-form-component>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title', config('app.name')) | Barbacoas</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/2.5.94/css/materialdesignicons.min.css">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">

        <nav class="navbar is-dark container" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="/">
                        inicio
                    </a>
                    @auth
                        <a href="{{ route('reservations.byUser') }}" class="navbar-item">Mis Reservaciones</a>
                        <a href="{{ route('barbecues.byUser') }}" class="navbar-item">Mis Barbacoas</a>
                        <a href="{{ route('barbecues.create') }}" class="navbar-item">Agregar Barbacoa</a>
                    @endauth
                </div>

                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="buttons">
                            @guest
                                <a class="button is-light" href="{{ route('login') }}">
                                    <strong>{{ __('Login') }}</strong>
                                </a>
                            @else
                                <a class="button is-light">
                                    {{ Auth::user()->name }}
                                </a>
                                <a class="button is-light" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            @endguest
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        <div>
            @yield('content')
        </div>

        <footer class="footer">
            <div class="content has-text-centered">
                <p>
                    Por <strong>Carlos Peñalba. </strong><a href="https://bulma.io">Construido Con Bulma.</a> 2019
                </p>
            </div>
        </footer>

    </div>
</body>
</html>

resources/views/reservation/show-by-user.blade.php
@extends('layouts.master')

@section('title')
    Reservaciones
@endsection

@section('content')

    <section class="section">
        <div class="container">
            <h1 class="title">Barbacoas Reservadas</h1>
        </div>
    </section>

    <div class="container">
        @foreach ($reservations->chunk(4) as $chunk)
            <div class="columns">
                @foreach ($chunk as $item)
                    <div class="column is-3">
                        <div class="card custom-card">
                            <div class="card-image">
                                <figure class="image is-4by3">
                                    <img src="{{ $item->barbecue->image_url }}" alt="Placeholder image">
                                </figure>
                            </div>
                            <div class="card-content">
                                <div class="media">
                                    <div class="media-left">
                                        <figure class="image is-48x48">
                                            <img src="{{ asset('images/user.png') }}" alt="Placeholder image">
                                        </figure>
                                    </div>
                                    <div class="media-content">
                                        <p class="title is-4">{{ $item->barbecue->name }}</p>
                                        <p class="subtitle is-6">{{ $item->barbecue->owner->name }}</p>
                                    </div>
                                </div>

                                <div class="content">
                                    <p><time>{{ $item->date }}</time></p>
                                    <p><time>{{ $item->hour_start }} - {{ $item->hour_end }}</time></p>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        @endforeach
    </div>

@endsection